"""Add table Tarefa

Revision ID: 03e2ed26c960
Revises: 3b25042ad5d7
Create Date: 2026-03-15 19:14:58.189496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e2ed26c960'
down_revision: Union[str, Sequence[str], None] = '3b25042ad5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', 
        sa.Enum('Pendente', 'Em andamento', 'Cancelada', 'Concluída', name="status_tarefa_enum"), 
        nullable=False
    ),
    sa.Column('prioridade', 
        sa.Enum('Baixa', 'Média', 'Alta', name='prioridade_tarefa_enum'),
        nullable=True
    ),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_limite', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('mutante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mutante_id'], ['mutantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefas')
    # ### end Alembic commands ###
