"""Create all tables

Revision ID: 188f187287b9
Revises: 
Create Date: 2026-02-11 10:11:01.297126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188f187287b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materias', 'professor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'materias', ['nome'])
    op.alter_column('mutantes', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('mutantes', 'senha',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('mutantes', 'poder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mutantes', 'turma_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'mutantes', ['email'])
    op.create_unique_constraint(None, 'mutantes', ['matricula'])
    op.add_column('mutantesmaterias', sa.Column('mutante', sa.Integer(), nullable=True))
    op.alter_column('mutantesmaterias', 'nota1',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'nota2',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_aluno'), 'mutantesmaterias', type_='foreignkey')
    op.create_foreign_key(None, 'mutantesmaterias', 'mutantes', ['mutante'], ['id'])
    op.drop_column('mutantesmaterias', 'mutante_id')
    op.alter_column('observacoes', 'observacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint(op.f('fk_mutantemateria'), 'observacoes', type_='foreignkey')
    op.drop_column('observacoes', 'mutantesmaterias_id')
    op.drop_column('observacoes', 'data')
    op.create_unique_constraint(None, 'poderes', ['nome'])
    op.alter_column('professores', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('professores', 'senha',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'professores', ['usuario'])
    op.alter_column('turmas', 'turma',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=15),
               nullable=True)
    op.drop_column('turmas', 'serie')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turmas', sa.Column('serie', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.alter_column('turmas', 'turma',
               existing_type=sa.String(length=15),
               type_=sa.CHAR(length=1),
               nullable=False)
    op.drop_constraint(None, 'professores', type_='unique')
    op.alter_column('professores', 'senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('professores', 'usuario',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'poderes', type_='unique')
    op.add_column('observacoes', sa.Column('data', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('observacoes', sa.Column('mutantesmaterias_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_mutantemateria'), 'observacoes', 'mutantesmaterias', ['mutantesmaterias_id'], ['id'])
    op.alter_column('observacoes', 'observacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('mutantesmaterias', sa.Column('mutante_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mutantesmaterias', type_='foreignkey')
    op.create_foreign_key(op.f('fk_aluno'), 'mutantesmaterias', 'mutantes', ['mutante_id'], ['id'])
    op.alter_column('mutantesmaterias', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantesmaterias', 'nota2',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'nota1',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.drop_column('mutantesmaterias', 'mutante')
    op.drop_constraint(None, 'mutantes', type_='unique')
    op.drop_constraint(None, 'mutantes', type_='unique')
    op.alter_column('mutantes', 'turma_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantes', 'poder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantes', 'senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('mutantes', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_constraint(None, 'materias', type_='unique')
    op.alter_column('materias', 'professor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
