"""Add 'chave_seguranca' into mutantes and remove Poder table

Revision ID: 3b25042ad5d7
Revises: 6b95d54e309a
Create Date: 2026-03-03 11:09:40.578569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b25042ad5d7'
down_revision: Union[str, Sequence[str], None] = '6b95d54e309a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_poder'), 'mutantes', type_='foreignkey')
    op.execute("DROP TABLE poderes CASCADE")
    op.drop_column('mutantes', 'poder_id')
    op.add_column('mutantes', sa.Column('chave_seguranca', sa.String(length=30), nullable=True))
    # op.alter_column('mutantes', 'esta_ativo',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mutantes', sa.Column('poder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_poder'), 'mutantes', 'poderes', ['poder_id'], ['id'])
    # op.alter_column('mutantes', 'esta_ativo',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    op.drop_column('mutantes', 'chave_seguranca')
    op.create_table('poderes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('poderes_pkey')),
    sa.UniqueConstraint('nome', name=op.f('poderes_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
