"""nome, email, senha now can be null

Revision ID: 6b95d54e309a
Revises: cbcc03641907
Create Date: 2026-02-20 16:37:47.812488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b95d54e309a'
down_revision: Union[str, Sequence[str], None] = 'cbcc03641907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
               DROP VIEW IF EXISTS Materias_Professores;
                DROP VIEW IF EXISTS Mutantes_Poderes;
                DROP VIEW IF EXISTS Mutantes_Turmas;
                DROP VIEW IF EXISTS Visao_Geral;
               """)
    op.alter_column('materias', 'professor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'materias', ['nome'])
    op.alter_column('mutantes', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('mutantes', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('mutantes', 'senha',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('mutantes', 'poder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mutantes', 'turma_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'mutantes', ['matricula'])
    op.create_unique_constraint(None, 'mutantes', ['email'])
    op.alter_column('mutantesmaterias', 'nota1',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'nota2',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'mutante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mutantesmaterias', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('observacoes', 'mutantesmaterias_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'poderes', ['nome'])
    op.alter_column('professores', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('professores', 'senha',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'professores', ['usuario'])
    op.alter_column('turmas', 'turma',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.execute("""
        CREATE VIEW Materias_Professores AS (
            SELECT 
                p.nome AS professor,
                m.nome AS materia
            FROM professores p
            JOIN materias m
                ON m.professor_id = p.id
        );

        CREATE VIEW Visao_Geral AS (
            SELECT 
                a.nome AS nome_mutante,
                CONCAT(t.serie, 'º', t.turma) AS turma,
                a.matricula,
                p.nome AS professor,
                mt.nome AS materia,
                o.observacao AS obs,
                o.data AS data_obs,
                mm.nota1,
                mm.nota2
            FROM mutantes a
            JOIN mutantesmaterias mm
                ON mm.mutante_id = a.id
            JOIN materias mt 
                ON mm.materia_id = mt.id
            JOIN observacoes o
                ON o.mutantesmaterias_id = mm.id
            JOIN professores p 
                ON mt.professor_id = p.id
            JOIN turmas t
                ON a.turma_id = t.id
        );
        CREATE VIEW Mutantes_Poderes AS (
            SELECT 
                m.id AS id_aluno,
                m.nome,
                p.nome AS poder
            FROM mutantes m 
            JOIN poderes p 
                ON m.poder_id = p.id
        );

        CREATE VIEW Mutantes_Turmas AS (
            SELECT 
                m.id AS id_mutante,
                m.nome,
                t.serie,
                t.turma,
                CONCAT(t.serie,'º',t.turma) AS turma_concat
            FROM mutantes m 
            JOIN turmas t
                ON m.turma_id = t.id
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turmas', 'turma',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.drop_constraint(None, 'professores', type_='unique')
    op.alter_column('professores', 'senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('professores', 'usuario',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'poderes', type_='unique')
    op.alter_column('observacoes', 'mutantesmaterias_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantesmaterias', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantesmaterias', 'mutante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantesmaterias', 'nota2',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'nota1',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'mutantes', type_='unique')
    op.drop_constraint(None, 'mutantes', type_='unique')
    op.alter_column('mutantes', 'turma_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantes', 'poder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantes', 'senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('mutantes', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('mutantes', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'materias', type_='unique')
    op.alter_column('materias', 'professor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
