"""Add new column 'esta_ativo' into Mutantes

Revision ID: cbcc03641907
Revises: 
Create Date: 2026-02-20 10:19:58.778434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcc03641907'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS visao_geral")
    op.alter_column('materias', 'professor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'materias', ['nome'])
    op.add_column('mutantes', sa.Column('esta_ativo', sa.Boolean(), nullable=True))
    op.alter_column('mutantes', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('mutantes', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('mutantes', 'senha',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('mutantes', 'poder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mutantes', 'turma_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'mutantes', ['email'])
    op.create_unique_constraint(None, 'mutantes', ['matricula'])
    op.alter_column('mutantesmaterias', 'nota1',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'nota2',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'mutante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mutantesmaterias', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('observacoes', 'mutantesmaterias_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'poderes', ['nome'])
    op.alter_column('professores', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('professores', 'senha',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'professores', ['usuario'])
    op.alter_column('turmas', 'turma',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.execute("""
        CREATE VIEW visao_geral AS
        SELECT 
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turmas', 'turma',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.drop_constraint(None, 'professores', type_='unique')
    op.alter_column('professores', 'senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('professores', 'usuario',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'poderes', type_='unique')
    op.alter_column('observacoes', 'mutantesmaterias_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantesmaterias', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantesmaterias', 'mutante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantesmaterias', 'nota2',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('mutantesmaterias', 'nota1',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'mutantes', type_='unique')
    op.drop_constraint(None, 'mutantes', type_='unique')
    op.alter_column('mutantes', 'turma_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantes', 'poder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mutantes', 'senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('mutantes', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('mutantes', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('mutantes', 'esta_ativo')
    op.drop_constraint(None, 'materias', type_='unique')
    op.alter_column('materias', 'professor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
